### PR TITLE
Implement delete change surround

### PR DESCRIPTION
**Pull request by shemerey**
Hi there, I've implemented `Change` and `Delete` surround. Can we discuss it ? I am not sure about performance side of my solution and it defiantly has some corner cases, but it works for me.

I don't have much experience with testing in  `Atom` if you can help me with this it would be grate.

What has been done so far: 

- [x] Change surround by `c s`
- [x] Delete surround by `d s`

### Known issues
`vim-mode` will change paragraph if you press `c s {` without target surround.

### CODE REVIEW

**Comment by gepoch** [comment]
Hey! Thanks for the pull request! I'm hoping to get this merged today. I'll keep you posted! :)

**Comment by shemerey** [comment]
:+1:

**Comment by gepoch** [comment]
Fantastic!

Thank you so much for the PR! Works like a charm. You are a hero to the vim refugees of atom!

**Comment by gepoch** [comment]
Out in v0.7.0, in case that wasn't obvious :)

**Comment by shemerey** [comment]
awesome :) I'll continue to improve it when have time

**Comment by gepoch** [comment]
Eventually, I'd like to take some time to reimplement things around the actual vim-mode service by pushing symbols into its stack (rather than dynamically generating all desired commands at load time) similar to the way it processes repeated arguments, etc.

But I think the next step is to iterate on specs! I'm not extremely familiar with writing jasmine specs for Atom, though. That's gonna have to change :) Especially if I'm planning on refactoring!

**Comment by shemerey** [comment]
Yes, I don't have experience with specs for atom as well, and now we have lack of specs and tons of functionality :) 

I've tried to copy and paste specs from `vim-mode` for instance https://github.com/atom/vim-mode/blob/master/spec/text-objects-spec.coffee#L167 but have no time to make it work.

BTW,  can you update README and update TODO section since we do support `d s` and `c s`

**Comment by gepoch** [comment]
Ah! Good point. I'll take care of that.

**Pull request merged**
